version: 2.1
orbs:
  lambdatest: lambdatest/lambda-tunnel@1.0.4
workflows:
  test-workflow:
    jobs:
      - lambdatest/with_tunnel:
          name: TEST test
          tunnel_name: test-selenium-tests
          lambdatest_email: nic@ada.support
          lambdatest_key: LAMBDA_TEST_KEY
          steps:
            - run:
                command: |
                  yarn
                  export LAMBDATEST_USERNAME=$LAMBDA_TEST_USER
                  yarn ci
